# Generated by Django 3.0.6 on 2020-05-09 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200510_0015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryProduct',
            new_name='ProductCategory',
        ),
    ]
